require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'ProjectFinal' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ProjectFinalTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
end

target 'ProjectFinal-tvOS' do
  # Pods for ProjectFinal-tvOS

  target 'ProjectFinal-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
